apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-secrets
  namespace: slotter
spec:
  provider: gcp

  parameters: # <── tells CSI which SM secrets to pull
    secrets: |
      - resourceName: "projects/slotter-457502/secrets/postgres-password"
        fileName: "POSTGRES_PASSWORD"
      - resourceName: "projects/slotter-457502/secrets/redis-password"
        fileName: "REDIS_PASSWORD"
      - resourceName: "projects/slotter-457502/secrets/jwt-secret-key"
        fileName: "JWT_SECRET_KEY"
      - resourceName: "projects/slotter-457502/secrets/gcp-project-id"
        fileName: "GCP_PROJECT_ID"
      - resourceName: "projects/slotter-457502/secrets/sendgrid-api-key"
        fileName: "SENDGRID_API_KEY"
      - resourceName: "projects/slotter-457502/secrets/twilio-account-sid"
        fileName: "TWILIO_ACCOUNT_SID"
      - resourceName: "projects/slotter-457502/secrets/twilio-auth-token"
        fileName: "TWILIO_AUTH_TOKEN"
      - resourceName: "projects/slotter-457502/secrets/twilio-recovery-code"
        fileName: "TWILIO_RECOVERY_CODE"
      - resourceName: "projects/slotter-457502/secrets/rabbitmq-password"
        fileName: "RABBITMQ_DEFAULT_PASS"

  secretObjects: # <── re‑creates the K8s Secret your pod already uses
    - secretName: backend-slotter-secrets # must match Deployment
      type: Opaque
      data:
        - key: POSTGRES_PASSWORD
          objectName: POSTGRES_PASSWORD
        - key: REDIS_PASSWORD
          objectName: REDIS_PASSWORD
        - key: JWT_SECRET_KEY
          objectName: JWT_SECRET_KEY
        - key: GCP_PROJECT_ID
          objectName: GCP_PROJECT_ID
        - key: SENDGRID_API_KEY
          objectName: SENDGRID_API_KEY
        - key: TWILIO_ACCOUNT_SID
          objectName: TWILIO_ACCOUNT_SID
        - key: TWILIO_AUTH_TOKEN
          objectName: TWILIO_AUTH_TOKEN
        - key: TWILIO_RECOVERY_CODE
          objectName: TWILIO_RECOVERY_CODE
        - key: RABBITMQ_DEFAULT_PASS
          objectName: RABBITMQ_DEFAULT_PASS
