apiVersion: v1
kind: Service
metadata:
  name: backend-slotter
  namespace: slotter
spec:
  type: ClusterIP
  selector:
    app: backend-slotter
  ports:
    - name: http
      port: 8080
      targetPort: 8080
