apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rabbitmq-secrets
  namespace: messaging
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/slotter-457502/secrets/rabbitmq-user"
        fileName: "RABBITMQ_DEFAULT_USER"
      - resourceName: "projects/slotter-457502/secrets/rabbitmq-password"
        fileName: "RABBITMQ_DEFAULT_PASS"

  secretObjects:
    - secretName: rabbitmq-auth
      type: Opaque
      data:
        - key: RABBITMQ_DEFAULT_USER
          objectName: RABBITMQ_DEFAULT_USER
        - key: RABBITMQ_DEFAULT_PASS
          objectName: RABBITMQ_DEFAULT_PASS

      syncSecret: true # ← moved up one level
