apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rabbitmq-secrets
  namespace: messaging
spec:
  provider: gcp

  # ——— which Secret‑Manager entries to pull ———
  parameters:
    secrets: |
      - resourceName: "projects/slotter-457502/secrets/rabbitmq-user"
        fileName: "RABBITMQ_DEFAULT_USER"
      - resourceName: "projects/slotter-457502/secrets/rabbitmq-password"
        fileName: "RABBITMQ_DEFAULT_PASS"

  # ——— have the driver *also* create a K8s Secret ———
  secretObjects:
    - secretName: rabbitmq-auth # will live in the same namespace
      type: Opaque
      data:
        - key: RABBITMQ_DEFAULT_USER # key inside the K8s Secret
          objectName: RABBITMQ_DEFAULT_USER # filename pulled from CSI mount
        - key: RABBITMQ_DEFAULT_PASS
          objectName: RABBITMQ_DEFAULT_PASS
