apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: messaging
spec:
  type: ClusterIP
  selector: { app: rabbitmq }
  ports:
    - { name: amqp, port: 5672, targetPort: 5672 }
    - { name: http, port: 15672, targetPort: 15672 }
---
# headless for pod‑to‑pod clustering
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-internal
  namespace: messaging
spec:
  clusterIP: None
  selector: { app: rabbitmq }
  ports:
    - { name: peer, port: 25672 }
